Repository redBorder/redborder-common, pull requests merged in 2023-11, with the labels that each got.

#2 RHEL9
  packaging/rpm/redborder-common.spec
Labels: kind/bug, size/XS

#3 Missing mac_vendors in /etc/objects/
  packaging/rpm/redborder-common.spec
  resources/etc/objects/mac_vendors
Labels: kind/bug, size/XXL

#4 Release 1.0.2
  packaging/rpm/redborder-common.spec
Labels: size/XS, kind/documentation
